version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tailoring_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tailoring_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: tailoring_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: tailoring_db
      DB_USER: admin
      DB_PASSWORD: admin
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    command: ["npm", "start"]

volumes:
  pgdata: